Small update on compose files
hulilabs/webdriverio pull request #5
Opened 2017-04-12 12:05 UTC by MichalDulemba

I added additional info for troubleshooting and compose version for VNC versions of selenium.

2017-04-17 17:38 UTC, marconn requested changes
Hi @MichalDulemba, thanks for contributing to these repo
I requested some little changes in order to keep things clean and ready to use
Please check feedback.

2017-04-17 17:38 UTC, mhnavarro commented on basiccompose.txt
> +version: '2'
Please change the extension for this file to .yml so it can be used as a base for other users

2017-04-17 17:38 UTC, mhnavarro commented on README.md
> +    before: function() {
Please put this in code context so it can be read easily
```
example
```

2017-04-17 17:38 UTC, mhnavarro commented on vnccompose.txt
> +version: '2'
Please change the extension for this file to .yml so it can be used as a base for other users

2017-04-18 07:37 UTC, MichalDulemba commented on README.md
> +    before: function() {
Moved to another file

2017-04-18 07:37 UTC, MichalDulemba commented
Will send another pull request

2017-04-18 08:17 UTC, closed without merging